### PR TITLE
 add initial version of ebclfsa qemu image

### PR DESCRIPTION
**Pull request by MofX**
This adds an image with two VMs running on the hypervisor.
The low integrity vm is a usual baseos vm with crinit and elos.
The high integrity vm has no applications installed at the moment. Just the
minimal bootstrap rootfs with busybox is installed and the kernel falls back to starting sh.

**Note that this a first preview and the documentation (aside from source comments) is missing. For instructions how to test this, please contact me directly, because it cannot work out-of-the-box right now**
See also: Elektrobit/ebcl_build_tools#18

### CODE REVIEW

**Review by thir820 — DISMISSED** [review]

**Comment by thir820** [comment]
@antonjahn Seems we finally hit a limit for the download volume.

**Comment by MofX** [comment]
Updated to upcoming version 1.4

**Comment by yaga271398** [comment]
The test for this PR was done in ticket https://jira.elektrobit.com/browse/EBLINUX-26377. The Base OS and HI VMs start successfully, and using CTRL+E with 0 or 1, I can switch between the Base OS VM and the HI VM. For more details, please refer to the ticket comments and attachments.

**Comment by MofX** [comment]
Superseded by #57

**Pull request closed without merging**
