### PR TITLE
Add a qt app for qemu amd64 systemd image

### PR DESCRIPTION
**Pull request by JiyangLiuG**
# Changes

Add qt app for qemu amd64 system image usage

# Dependencies:

_(Provide list of pull requests with dependecies with this pull request)_

# Tests results

```bash
<!-- add Robot test CLI logs here. -->
```

# Developer Checklist:

- [ ] Test: Changes are tested
- [ ] Doc: Documentation has been updated 
- [x] Git: Informative git commit message(s)
- [ ] Issue: If a related GitHub issue exists, linking is done

## Checklists for documentation

- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object

# Reviewer checklist:

- [x] Review: Changes are reviewed
- [ ] Review: Tested by the reviewer

## Checklists for documentation

- [ ] Grammar: the content is grammatically correct
      (spelling, grammar, formatting, US English is used)
- [ ] Comprehensibility/Unambiguousness: the content is easy readable, clear to understand
- [ ] Correctness and consistency: the content is technically correct and consistent,
      no contradictions, no double descriptions
- [ ] Terminology: technical terms are clear and they are used correctly and documented in the glossary
- [ ] Level of detail: the content matches the detail level necessary for the reviewed object

### CODE REVIEW

**Comment by MofX** [comment]
This PR should be changed to target main_1.x

**Review by simone-weiss — COMMENTED** [review]
Please also consider added cmake preset stuff

**Comment by JiyangLiuG** [comment]
> Please also consider added cmake preset stuff

https://github.com/Elektrobit/ebcl_template/pull/59/files#diff-910c78ee6fed6458cd02f00239eac90c1f4d48e7513166eb84b756d50d9936ee :)

**Comment by JiyangLiuG** [comment]
This pull request is shall not be merged, because it changes the apt_repo to 
ubuntu repos: https://github.com/Elektrobit/ebcl_template/pull/59/files#diff-a61d00ebb484258fc702f6197c32e6867cd35f674004617b56615dffc4d68cf0

Other then that, is tested to be success.

**Review by thir820 — APPROVED** [review]

**Comment by thir820** [comment]
Merging image to 2.x line. The images on the 2.x line need to be aligned and the documentation updated, therefore skipping documentation for now.

**Pull request merged**
