### PR TITLE
EBcL 1.2

### PR DESCRIPTION
**Pull request by thir820**

### CODE REVIEW

**Comment by ulbu261833** [comment]
Shouldn't the version in the appliance.kiwi files be adapted, too?

**Comment by ulbu261833** [comment]
Why are the changes at elosd.json only done for x86_64 but not for aarch64?

**Comment by thir820** [comment]
> Why are the changes at elosd.json only done for x86_64 but not for aarch64?

Result of debugging elos errors, but the difference doesn't matter.

**Review by ulbu261833 — CHANGES_REQUESTED** [review]
build of demo app my-json-app is failing - see https://git.elektrobitautomotive.com/Innovation/Inno2023-017_EBcL-SDK/actions/runs/5460

**Comment by thir820** [comment]
> build of demo app my-json-app is failing - see https://git.elektrobitautomotive.com/Innovation/Inno2023-017_EBcL-SDK/actions/runs/5460

Fixed.

**Pull request merged**
