### PR TITLE
Cmake preset-based application development workflow

### PR DESCRIPTION
**Pull request by matthiasb85**
The following features have been implemented:

- added required packages to ebcl server image
- cmake presets
- added deployment tasks
- added separate workspace root for applications
- added gdb port forwarding to qemu x86_64 command
- fixed usage of DESTDIR and CMAKE_INSTALL_PREFIX
- fixed sysroot_install make target
- added second application (meminfo, implementation done by @simone-weiss  :-)) to show case development workflow

**Todos**

- [x] add required packages to all relevant image configurations
- [x] add gdb port forward to all relevant make targets
- [x] add some kind of documentation
- [x] have https://github.com/Elektrobit/ebcl_dev_container/pull/6 merged and tagged

### CODE REVIEW

**Review by thir820 — APPROVED** [review]

**Comment by thir820** [comment]
@matthiasb85 I will take care of "add required packages to all relevant image configurations"

**Comment by thir820** [comment]
Images pushed, ToDos:
[ ] test pi4 image builds
[ ] test rdb2 image builds
[ ] test app depoly

**Comment by simone-weiss** [comment]
> Images pushed, ToDos: [ ] test pi4 image builds [ ] test rdb2 image builds [ ] test app depoly

will take care of this

**Comment by simone-weiss** [comment]
> > Images pushed, ToDos: [ ] test pi4 image builds [ ] test rdb2 image builds [ ] test app depoly
> 
> will take care of this

done ok

**Pull request merged**
